# This file was generated by MOLE 2.0 (http://mole.chemi.muni.cz, http://mole.upol.cz - moleOnline, version 2.5.17.4.24)
# Please cite the following reference when reporting the results using MOLE:
#
# Sehnal D., Svobodova Varekova R., Berka K., Pravda L., Navratilova V., Banas P., Ionescu C.-M., Geidl S., Otyepka M., Koca J.:
# MOLE 2.0: Advanced Approach for Analysis of Biomacromolecular Channels. Journal of Cheminformatics 2013, 5:39. doi:10.1186/1758-2946-5-39
#
# and
#
# Berka, K; Hanak, O; Sehnal, D; Banas, P; Navratilova, V; Jaiswal, D; Ionescu, C-M; Svobodova Varekova, R; Koca, J; Otyepka M:
# MOLEonline 2.0: Interactive Web-based Analysis of Biomacromolecular Channels. Nucleic Acid Research 2012, doi:10.1093/nar/GKS363
#
from pymol import cmd
from chempy.models import Indexed
from chempy import Bond, Atom

def Tunnels1():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.7816
   at.coord = [129.1871, 133.9541, 158.6493]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.7558
   at.coord = [129.2604, 133.8610, 158.7362]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.7374
   at.coord = [129.3329, 133.7698, 158.8225]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.7272
   at.coord = [129.4033, 133.6827, 158.9075]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.7279
   at.coord = [129.4709, 133.6015, 158.9905]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.7123
   at.coord = [129.5345, 133.5282, 159.0708]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.6942
   at.coord = [129.5933, 133.4649, 159.1479]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.6873
   at.coord = [129.6463, 133.4135, 159.2209]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.6918
   at.coord = [129.6924, 133.3760, 159.2894]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 1.7075
   at.coord = [129.7308, 133.3544, 159.3526]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 1.7344
   at.coord = [129.7604, 133.3507, 159.4098]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 1.7726
   at.coord = [129.7806, 133.3662, 159.4605]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 1.8199
   at.coord = [129.7938, 133.3967, 159.5042]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 1.8007
   at.coord = [129.8042, 133.4343, 159.5407]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 1.7574
   at.coord = [129.8161, 133.4713, 159.5699]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 1.7224
   at.coord = [129.8337, 133.5001, 159.5914]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 1.7022
   at.coord = [129.8612, 133.5128, 159.6052]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 1.7031
   at.coord = [129.9027, 133.5018, 159.6109]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 1.7335
   at.coord = [129.9627, 133.4594, 159.6084]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 1.8016
   at.coord = [130.0452, 133.3777, 159.5974]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 1.8736
   at.coord = [130.1544, 133.2491, 159.5777]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 1.8072
   at.coord = [130.2946, 133.0661, 159.5492]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 1.7176
   at.coord = [130.4648, 132.8292, 159.5121]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 1.6357
   at.coord = [130.6582, 132.5483, 159.4673]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 1.5786
   at.coord = [130.8679, 132.2343, 159.4160]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 1.5593
   at.coord = [131.0867, 131.8977, 159.3590]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.5853
   at.coord = [131.3075, 131.5491, 159.2974]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.6562
   at.coord = [131.5232, 131.1993, 159.2322]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.7638
   at.coord = [131.7268, 130.8589, 159.1643]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.8944
   at.coord = [131.9111, 130.5385, 159.0946]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 2.0307
   at.coord = [132.0691, 130.2487, 159.0243]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 2.1535
   at.coord = [132.1937, 130.0003, 158.9543]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 2.2512
   at.coord = [132.2807, 129.7996, 158.8856]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 2.2489
   at.coord = [132.3337, 129.6420, 158.8190]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 2.2160
   at.coord = [132.3575, 129.5211, 158.7555]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 2.2195
   at.coord = [132.3568, 129.4305, 158.6960]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 2.2456
   at.coord = [132.3364, 129.3638, 158.6413]
   model.atom.append(at)
   at = Atom()
   at.name = "37"
   at.vdw = 2.2892
   at.coord = [132.3011, 129.3146, 158.5924]
   model.atom.append(at)
   at = Atom()
   at.name = "38"
   at.vdw = 2.2972
   at.coord = [132.2558, 129.2765, 158.5501]
   model.atom.append(at)
   at = Atom()
   at.name = "39"
   at.vdw = 2.2525
   at.coord = [132.2051, 129.2430, 158.5154]
   model.atom.append(at)
   at = Atom()
   at.name = "40"
   at.vdw = 2.2124
   at.coord = [132.1540, 129.2078, 158.4891]
   model.atom.append(at)
   at = Atom()
   at.name = "41"
   at.vdw = 2.1796
   at.coord = [132.1071, 129.1644, 158.4722]
   model.atom.append(at)
   at = Atom()
   at.name = "42"
   at.vdw = 2.1603
   at.coord = [132.0686, 129.1074, 158.4654]
   model.atom.append(at)
   at = Atom()
   at.name = "43"
   at.vdw = 2.1544
   at.coord = [132.0381, 129.0380, 158.4691]
   model.atom.append(at)
   at = Atom()
   at.name = "44"
   at.vdw = 2.1594
   at.coord = [132.0137, 128.9596, 158.4834]
   model.atom.append(at)
   at = Atom()
   at.name = "45"
   at.vdw = 2.1727
   at.coord = [131.9933, 128.8757, 158.5083]
   model.atom.append(at)
   at = Atom()
   at.name = "46"
   at.vdw = 2.1914
   at.coord = [131.9750, 128.7898, 158.5439]
   model.atom.append(at)
   at = Atom()
   at.name = "47"
   at.vdw = 2.2126
   at.coord = [131.9568, 128.7055, 158.5904]
   model.atom.append(at)
   at = Atom()
   at.name = "48"
   at.vdw = 2.2332
   at.coord = [131.9366, 128.6261, 158.6478]
   model.atom.append(at)
   at = Atom()
   at.name = "49"
   at.vdw = 2.2502
   at.coord = [131.9126, 128.5553, 158.7163]
   model.atom.append(at)
   at = Atom()
   at.name = "50"
   at.vdw = 2.2604
   at.coord = [131.8827, 128.4964, 158.7958]
   model.atom.append(at)
   at = Atom()
   at.name = "51"
   at.vdw = 2.2608
   at.coord = [131.8449, 128.4531, 158.8866]
   model.atom.append(at)
   at = Atom()
   at.name = "52"
   at.vdw = 2.2487
   at.coord = [131.7974, 128.4285, 158.9887]
   model.atom.append(at)
   at = Atom()
   at.name = "53"
   at.vdw = 2.2264
   at.coord = [131.7414, 128.4215, 159.1014]
   model.atom.append(at)
   at = Atom()
   at.name = "54"
   at.vdw = 2.2000
   at.coord = [131.6807, 128.4272, 159.2232]
   model.atom.append(at)
   at = Atom()
   at.name = "55"
   at.vdw = 2.1757
   at.coord = [131.6190, 128.4408, 159.3529]
   model.atom.append(at)
   at = Atom()
   at.name = "56"
   at.vdw = 2.1594
   at.coord = [131.5601, 128.4572, 159.4890]
   model.atom.append(at)
   at = Atom()
   at.name = "57"
   at.vdw = 2.1569
   at.coord = [131.5079, 128.4715, 159.6302]
   model.atom.append(at)
   at = Atom()
   at.name = "58"
   at.vdw = 2.1733
   at.coord = [131.4661, 128.4787, 159.7751]
   model.atom.append(at)
   at = Atom()
   at.name = "59"
   at.vdw = 2.2129
   at.coord = [131.4385, 128.4741, 159.9224]
   model.atom.append(at)
   at = Atom()
   at.name = "60"
   at.vdw = 2.2801
   at.coord = [131.4289, 128.4525, 160.0706]
   model.atom.append(at)
   at = Atom()
   at.name = "61"
   at.vdw = 2.3770
   at.coord = [131.4411, 128.4090, 160.2184]
   model.atom.append(at)
   at = Atom()
   at.name = "62"
   at.vdw = 2.5024
   at.coord = [131.4789, 128.3388, 160.3645]
   model.atom.append(at)
   at = Atom()
   at.name = "63"
   at.vdw = 2.4752
   at.coord = [131.5438, 128.2396, 160.5079]
   model.atom.append(at)
   at = Atom()
   at.name = "64"
   at.vdw = 2.3550
   at.coord = [131.6335, 128.1138, 160.6490]
   model.atom.append(at)
   at = Atom()
   at.name = "65"
   at.vdw = 2.2566
   at.coord = [131.7453, 127.9645, 160.7878]
   model.atom.append(at)
   at = Atom()
   at.name = "66"
   at.vdw = 2.1777
   at.coord = [131.8762, 127.7945, 160.9248]
   model.atom.append(at)
   at = Atom()
   at.name = "67"
   at.vdw = 2.1223
   at.coord = [132.0237, 127.6069, 161.0602]
   model.atom.append(at)
   at = Atom()
   at.name = "68"
   at.vdw = 2.0946
   at.coord = [132.1850, 127.4045, 161.1943]
   model.atom.append(at)
   at = Atom()
   at.name = "69"
   at.vdw = 2.0972
   at.coord = [132.3573, 127.1903, 161.3273]
   model.atom.append(at)
   at = Atom()
   at.name = "70"
   at.vdw = 2.1315
   at.coord = [132.5378, 126.9672, 161.4594]
   model.atom.append(at)
   at = Atom()
   at.name = "71"
   at.vdw = 2.1965
   at.coord = [132.7238, 126.7383, 161.5910]
   model.atom.append(at)
   at = Atom()
   at.name = "72"
   at.vdw = 2.2902
   at.coord = [132.9126, 126.5064, 161.7224]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels1")
   cmd.hide("everything","Tunnels1")
   cmd.set("surface_color","red","Tunnels1")
   cmd.show("surface","Tunnels1")
Tunnels1()
def Tunnels2():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 2.0523
   at.coord = [133.2656, 138.0664, 121.9541]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 2.0735
   at.coord = [133.2863, 138.0412, 121.9591]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 2.0931
   at.coord = [133.3064, 138.0185, 121.9637]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 2.1095
   at.coord = [133.3253, 138.0009, 121.9676]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 2.1206
   at.coord = [133.3427, 137.9909, 121.9704]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 2.1255
   at.coord = [133.3577, 137.9912, 121.9718]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 2.1173
   at.coord = [133.3700, 138.0042, 121.9714]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 2.1067
   at.coord = [133.3790, 138.0324, 121.9689]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 2.0842
   at.coord = [133.3842, 138.0719, 121.9650]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 2.0652
   at.coord = [133.3857, 138.1072, 121.9629]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 2.0599
   at.coord = [133.3834, 138.1213, 121.9656]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 2.0798
   at.coord = [133.3772, 138.0973, 121.9764]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 2.1153
   at.coord = [133.3672, 138.0186, 121.9984]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 2.1215
   at.coord = [133.3534, 137.8681, 122.0349]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 2.1257
   at.coord = [133.3358, 137.6303, 122.0888]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 2.1427
   at.coord = [133.3165, 137.3130, 122.1573]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 2.2017
   at.coord = [133.2996, 136.9445, 122.2328]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 2.3073
   at.coord = [133.2891, 136.5540, 122.3075]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 2.4517
   at.coord = [133.2891, 136.1707, 122.3735]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 2.6156
   at.coord = [133.3036, 135.8237, 122.4229]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 2.7787
   at.coord = [133.3366, 135.5423, 122.4481]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 2.8318
   at.coord = [133.3912, 135.3508, 122.4420]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 2.7394
   at.coord = [133.4629, 135.2408, 122.4045]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 2.7260
   at.coord = [133.5440, 135.1896, 122.3385]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 2.7549
   at.coord = [133.6269, 135.1749, 122.2468]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 2.7462
   at.coord = [133.7040, 135.1738, 122.1320]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 2.7195
   at.coord = [133.7676, 135.1640, 121.9969]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 2.7361
   at.coord = [133.8100, 135.1227, 121.8444]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 2.6031
   at.coord = [133.8252, 135.0353, 121.6786]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 2.4946
   at.coord = [133.8116, 134.9105, 121.5079]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 2.4103
   at.coord = [133.7686, 134.7619, 121.3417]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 2.3662
   at.coord = [133.6955, 134.6028, 121.1891]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 2.3718
   at.coord = [133.5917, 134.4468, 121.0594]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 2.4327
   at.coord = [133.4566, 134.3072, 120.9618]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 2.5474
   at.coord = [133.2896, 134.1973, 120.9055]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 2.5197
   at.coord = [133.0949, 134.1222, 120.8915]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 2.4607
   at.coord = [132.8831, 134.0758, 120.9094]
   model.atom.append(at)
   at = Atom()
   at.name = "37"
   at.vdw = 2.4419
   at.coord = [132.6656, 134.0507, 120.9478]
   model.atom.append(at)
   at = Atom()
   at.name = "38"
   at.vdw = 2.4524
   at.coord = [132.4537, 134.0397, 120.9955]
   model.atom.append(at)
   at = Atom()
   at.name = "39"
   at.vdw = 2.4784
   at.coord = [132.2587, 134.0358, 121.0411]
   model.atom.append(at)
   at = Atom()
   at.name = "40"
   at.vdw = 2.5122
   at.coord = [132.0918, 134.0316, 121.0734]
   model.atom.append(at)
   at = Atom()
   at.name = "41"
   at.vdw = 2.4690
   at.coord = [131.9633, 134.0204, 121.0817]
   model.atom.append(at)
   at = Atom()
   at.name = "42"
   at.vdw = 2.4203
   at.coord = [131.8699, 134.0009, 121.0640]
   model.atom.append(at)
   at = Atom()
   at.name = "43"
   at.vdw = 2.3973
   at.coord = [131.7990, 133.9758, 121.0242]
   model.atom.append(at)
   at = Atom()
   at.name = "44"
   at.vdw = 2.3963
   at.coord = [131.7378, 133.9477, 120.9664]
   model.atom.append(at)
   at = Atom()
   at.name = "45"
   at.vdw = 2.3533
   at.coord = [131.6734, 133.9193, 120.8948]
   model.atom.append(at)
   at = Atom()
   at.name = "46"
   at.vdw = 2.3055
   at.coord = [131.5929, 133.8934, 120.8134]
   model.atom.append(at)
   at = Atom()
   at.name = "47"
   at.vdw = 2.2639
   at.coord = [131.4835, 133.8727, 120.7265]
   model.atom.append(at)
   at = Atom()
   at.name = "48"
   at.vdw = 2.2356
   at.coord = [131.3353, 133.8591, 120.6378]
   model.atom.append(at)
   at = Atom()
   at.name = "49"
   at.vdw = 2.2239
   at.coord = [131.1550, 133.8514, 120.5505]
   model.atom.append(at)
   at = Atom()
   at.name = "50"
   at.vdw = 2.2297
   at.coord = [130.9543, 133.8471, 120.4675]
   model.atom.append(at)
   at = Atom()
   at.name = "51"
   at.vdw = 2.2514
   at.coord = [130.7449, 133.8437, 120.3914]
   model.atom.append(at)
   at = Atom()
   at.name = "52"
   at.vdw = 2.2839
   at.coord = [130.5388, 133.8389, 120.3251]
   model.atom.append(at)
   at = Atom()
   at.name = "53"
   at.vdw = 2.3240
   at.coord = [130.3476, 133.8302, 120.2715]
   model.atom.append(at)
   at = Atom()
   at.name = "54"
   at.vdw = 2.3151
   at.coord = [130.1832, 133.8150, 120.2332]
   model.atom.append(at)
   at = Atom()
   at.name = "55"
   at.vdw = 2.3021
   at.coord = [130.0524, 133.7928, 120.2110]
   model.atom.append(at)
   at = Atom()
   at.name = "56"
   at.vdw = 2.3022
   at.coord = [129.9508, 133.7664, 120.2007]
   model.atom.append(at)
   at = Atom()
   at.name = "57"
   at.vdw = 2.3090
   at.coord = [129.8722, 133.7397, 120.1971]
   model.atom.append(at)
   at = Atom()
   at.name = "58"
   at.vdw = 2.3175
   at.coord = [129.8103, 133.7162, 120.1954]
   model.atom.append(at)
   at = Atom()
   at.name = "59"
   at.vdw = 2.3236
   at.coord = [129.7591, 133.6997, 120.1905]
   model.atom.append(at)
   at = Atom()
   at.name = "60"
   at.vdw = 2.3235
   at.coord = [129.7123, 133.6937, 120.1774]
   model.atom.append(at)
   at = Atom()
   at.name = "61"
   at.vdw = 2.3140
   at.coord = [129.6637, 133.7017, 120.1513]
   model.atom.append(at)
   at = Atom()
   at.name = "62"
   at.vdw = 2.2973
   at.coord = [129.6081, 133.7216, 120.1101]
   model.atom.append(at)
   at = Atom()
   at.name = "63"
   at.vdw = 2.2810
   at.coord = [129.5408, 133.7450, 120.0550]
   model.atom.append(at)
   at = Atom()
   at.name = "64"
   at.vdw = 2.2737
   at.coord = [129.4575, 133.7630, 119.9874]
   model.atom.append(at)
   at = Atom()
   at.name = "65"
   at.vdw = 2.2842
   at.coord = [129.3536, 133.7669, 119.9086]
   model.atom.append(at)
   at = Atom()
   at.name = "66"
   at.vdw = 2.3220
   at.coord = [129.2248, 133.7479, 119.8199]
   model.atom.append(at)
   at = Atom()
   at.name = "67"
   at.vdw = 2.3995
   at.coord = [129.0664, 133.6971, 119.7228]
   model.atom.append(at)
   at = Atom()
   at.name = "68"
   at.vdw = 2.4808
   at.coord = [128.8748, 133.6068, 119.6185]
   model.atom.append(at)
   at = Atom()
   at.name = "69"
   at.vdw = 2.4748
   at.coord = [128.6519, 133.4783, 119.5082]
   model.atom.append(at)
   at = Atom()
   at.name = "70"
   at.vdw = 2.4819
   at.coord = [128.4029, 133.3179, 119.3929]
   model.atom.append(at)
   at = Atom()
   at.name = "71"
   at.vdw = 2.5083
   at.coord = [128.1330, 133.1320, 119.2736]
   model.atom.append(at)
   at = Atom()
   at.name = "72"
   at.vdw = 2.5638
   at.coord = [127.8474, 132.9269, 119.1512]
   model.atom.append(at)
   at = Atom()
   at.name = "73"
   at.vdw = 2.6523
   at.coord = [127.5513, 132.7091, 119.0269]
   model.atom.append(at)
   at = Atom()
   at.name = "74"
   at.vdw = 2.7757
   at.coord = [127.2501, 132.4849, 118.9016]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels2")
   cmd.hide("everything","Tunnels2")
   cmd.set("surface_color","orange","Tunnels2")
   cmd.show("surface","Tunnels2")
Tunnels2()
def Tunnels3():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.7816
   at.coord = [129.1871, 133.9541, 158.6493]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.7323
   at.coord = [129.2016, 133.9249, 158.6029]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.6862
   at.coord = [129.2115, 133.8992, 158.5570]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.6464
   at.coord = [129.2118, 133.8803, 158.5122]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.6160
   at.coord = [129.1980, 133.8717, 158.4688]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.5984
   at.coord = [129.1651, 133.8767, 158.4274]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.5976
   at.coord = [129.1085, 133.8989, 158.3886]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.6179
   at.coord = [129.0235, 133.9416, 158.3527]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.6716
   at.coord = [128.9053, 134.0083, 158.3203]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 1.6694
   at.coord = [128.7494, 134.1022, 158.2920]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 1.5694
   at.coord = [128.5585, 134.2216, 158.2680]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 1.4948
   at.coord = [128.3419, 134.3604, 158.2489]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 1.4395
   at.coord = [128.1097, 134.5119, 158.2350]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 1.4137
   at.coord = [127.8715, 134.6697, 158.2267]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 1.4193
   at.coord = [127.6371, 134.8271, 158.2245]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 1.4542
   at.coord = [127.4166, 134.9776, 158.2286]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 1.5090
   at.coord = [127.2196, 135.1148, 158.2394]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 1.5810
   at.coord = [127.0559, 135.2320, 158.2575]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 1.5935
   at.coord = [126.9328, 135.3244, 158.2827]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 1.5779
   at.coord = [126.8467, 135.3941, 158.3136]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 1.5825
   at.coord = [126.7911, 135.4447, 158.3483]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 1.5998
   at.coord = [126.7600, 135.4799, 158.3849]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 1.6252
   at.coord = [126.7468, 135.5034, 158.4216]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 1.6537
   at.coord = [126.7455, 135.5189, 158.4566]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 1.6812
   at.coord = [126.7497, 135.5302, 158.4879]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 1.7035
   at.coord = [126.7531, 135.5408, 158.5136]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.7169
   at.coord = [126.7496, 135.5545, 158.5320]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.7209
   at.coord = [126.7365, 135.5722, 158.5435]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.7185
   at.coord = [126.7148, 135.5923, 158.5504]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.7130
   at.coord = [126.6854, 135.6131, 158.5553]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 1.7074
   at.coord = [126.6493, 135.6331, 158.5607]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 1.7049
   at.coord = [126.6076, 135.6504, 158.5691]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 1.7087
   at.coord = [126.5613, 135.6634, 158.5832]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 1.7223
   at.coord = [126.5115, 135.6705, 158.6053]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 1.7464
   at.coord = [126.4590, 135.6699, 158.6380]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 1.7928
   at.coord = [126.4049, 135.6612, 158.6835]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 1.7835
   at.coord = [126.3501, 135.6486, 158.7420]
   model.atom.append(at)
   at = Atom()
   at.name = "37"
   at.vdw = 1.7455
   at.coord = [126.2951, 135.6377, 158.8135]
   model.atom.append(at)
   at = Atom()
   at.name = "38"
   at.vdw = 1.7116
   at.coord = [126.2408, 135.6339, 158.8977]
   model.atom.append(at)
   at = Atom()
   at.name = "39"
   at.vdw = 1.6876
   at.coord = [126.1878, 135.6426, 158.9947]
   model.atom.append(at)
   at = Atom()
   at.name = "40"
   at.vdw = 1.6809
   at.coord = [126.1370, 135.6694, 159.1042]
   model.atom.append(at)
   at = Atom()
   at.name = "41"
   at.vdw = 1.6962
   at.coord = [126.0890, 135.7197, 159.2262]
   model.atom.append(at)
   at = Atom()
   at.name = "42"
   at.vdw = 1.7470
   at.coord = [126.0446, 135.7990, 159.3605]
   model.atom.append(at)
   at = Atom()
   at.name = "43"
   at.vdw = 1.7393
   at.coord = [126.0044, 135.9124, 159.5070]
   model.atom.append(at)
   at = Atom()
   at.name = "44"
   at.vdw = 1.6560
   at.coord = [125.9671, 136.0577, 159.6630]
   model.atom.append(at)
   at = Atom()
   at.name = "45"
   at.vdw = 1.5915
   at.coord = [125.9292, 136.2250, 159.8236]
   model.atom.append(at)
   at = Atom()
   at.name = "46"
   at.vdw = 1.5303
   at.coord = [125.8872, 136.4043, 159.9838]
   model.atom.append(at)
   at = Atom()
   at.name = "47"
   at.vdw = 1.4934
   at.coord = [125.8378, 136.5853, 160.1385]
   model.atom.append(at)
   at = Atom()
   at.name = "48"
   at.vdw = 1.4885
   at.coord = [125.7774, 136.7580, 160.2826]
   model.atom.append(at)
   at = Atom()
   at.name = "49"
   at.vdw = 1.5195
   at.coord = [125.7024, 136.9123, 160.4112]
   model.atom.append(at)
   at = Atom()
   at.name = "50"
   at.vdw = 1.5908
   at.coord = [125.6096, 137.0380, 160.5191]
   model.atom.append(at)
   at = Atom()
   at.name = "51"
   at.vdw = 1.6044
   at.coord = [125.4952, 137.1251, 160.6013]
   model.atom.append(at)
   at = Atom()
   at.name = "52"
   at.vdw = 1.5031
   at.coord = [125.3576, 137.1663, 160.6549]
   model.atom.append(at)
   at = Atom()
   at.name = "53"
   at.vdw = 1.4745
   at.coord = [125.2015, 137.1664, 160.6850]
   model.atom.append(at)
   at = Atom()
   at.name = "54"
   at.vdw = 1.4840
   at.coord = [125.0331, 137.1330, 160.6990]
   model.atom.append(at)
   at = Atom()
   at.name = "55"
   at.vdw = 1.5284
   at.coord = [124.8590, 137.0740, 160.7041]
   model.atom.append(at)
   at = Atom()
   at.name = "56"
   at.vdw = 1.5966
   at.coord = [124.6855, 136.9969, 160.7077]
   model.atom.append(at)
   at = Atom()
   at.name = "57"
   at.vdw = 1.6767
   at.coord = [124.5190, 136.9094, 160.7171]
   model.atom.append(at)
   at = Atom()
   at.name = "58"
   at.vdw = 1.7567
   at.coord = [124.3658, 136.8192, 160.7395]
   model.atom.append(at)
   at = Atom()
   at.name = "59"
   at.vdw = 1.8199
   at.coord = [124.2324, 136.7341, 160.7823]
   model.atom.append(at)
   at = Atom()
   at.name = "60"
   at.vdw = 1.8643
   at.coord = [124.1249, 136.6614, 160.8525]
   model.atom.append(at)
   at = Atom()
   at.name = "61"
   at.vdw = 1.7874
   at.coord = [124.0441, 136.6040, 160.9518]
   model.atom.append(at)
   at = Atom()
   at.name = "62"
   at.vdw = 1.7121
   at.coord = [123.9857, 136.5599, 161.0765]
   model.atom.append(at)
   at = Atom()
   at.name = "63"
   at.vdw = 1.6576
   at.coord = [123.9448, 136.5270, 161.2228]
   model.atom.append(at)
   at = Atom()
   at.name = "64"
   at.vdw = 1.6249
   at.coord = [123.9169, 136.5030, 161.3868]
   model.atom.append(at)
   at = Atom()
   at.name = "65"
   at.vdw = 1.6109
   at.coord = [123.8972, 136.4859, 161.5645]
   model.atom.append(at)
   at = Atom()
   at.name = "66"
   at.vdw = 1.6171
   at.coord = [123.8810, 136.4734, 161.7520]
   model.atom.append(at)
   at = Atom()
   at.name = "67"
   at.vdw = 1.6018
   at.coord = [123.8637, 136.4635, 161.9456]
   model.atom.append(at)
   at = Atom()
   at.name = "68"
   at.vdw = 1.5605
   at.coord = [123.8406, 136.4540, 162.1411]
   model.atom.append(at)
   at = Atom()
   at.name = "69"
   at.vdw = 1.5015
   at.coord = [123.8083, 136.4423, 162.3356]
   model.atom.append(at)
   at = Atom()
   at.name = "70"
   at.vdw = 1.4532
   at.coord = [123.7680, 136.4247, 162.5289]
   model.atom.append(at)
   at = Atom()
   at.name = "71"
   at.vdw = 1.4255
   at.coord = [123.7226, 136.3970, 162.7214]
   model.atom.append(at)
   at = Atom()
   at.name = "72"
   at.vdw = 1.4237
   at.coord = [123.6747, 136.3551, 162.9138]
   model.atom.append(at)
   at = Atom()
   at.name = "73"
   at.vdw = 1.4534
   at.coord = [123.6270, 136.2948, 163.1066]
   model.atom.append(at)
   at = Atom()
   at.name = "74"
   at.vdw = 1.5196
   at.coord = [123.5821, 136.2120, 163.3005]
   model.atom.append(at)
   at = Atom()
   at.name = "75"
   at.vdw = 1.6249
   at.coord = [123.5427, 136.1026, 163.4959]
   model.atom.append(at)
   at = Atom()
   at.name = "76"
   at.vdw = 1.7832
   at.coord = [123.5114, 135.9623, 163.6934]
   model.atom.append(at)
   at = Atom()
   at.name = "77"
   at.vdw = 1.9155
   at.coord = [123.4909, 135.7873, 163.8937]
   model.atom.append(at)
   at = Atom()
   at.name = "78"
   at.vdw = 1.9098
   at.coord = [123.4817, 135.5776, 164.0968]
   model.atom.append(at)
   at = Atom()
   at.name = "79"
   at.vdw = 1.9217
   at.coord = [123.4825, 135.3374, 164.3023]
   model.atom.append(at)
   at = Atom()
   at.name = "80"
   at.vdw = 1.9844
   at.coord = [123.4920, 135.0711, 164.5100]
   model.atom.append(at)
   at = Atom()
   at.name = "81"
   at.vdw = 2.0964
   at.coord = [123.5085, 134.7830, 164.7194]
   model.atom.append(at)
   at = Atom()
   at.name = "82"
   at.vdw = 2.2526
   at.coord = [123.5308, 134.4775, 164.9302]
   model.atom.append(at)
   at = Atom()
   at.name = "83"
   at.vdw = 2.4577
   at.coord = [123.5574, 134.1589, 165.1421]
   model.atom.append(at)
   at = Atom()
   at.name = "84"
   at.vdw = 2.6339
   at.coord = [123.5869, 133.8316, 165.3547]
   model.atom.append(at)
   at = Atom()
   at.name = "85"
   at.vdw = 2.7857
   at.coord = [123.6177, 133.4999, 165.5677]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels3")
   cmd.hide("everything","Tunnels3")
   cmd.set("surface_color","salmon","Tunnels3")
   cmd.show("surface","Tunnels3")
Tunnels3()
def Tunnels4():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 2.5941
   at.coord = [149.7245, 116.6239, 86.3544]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 2.5855
   at.coord = [149.8331, 116.5616, 86.4393]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 2.5857
   at.coord = [149.9406, 116.4976, 86.5183]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 2.5974
   at.coord = [150.0460, 116.4304, 86.5857]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 2.6231
   at.coord = [150.1482, 116.3583, 86.6355]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 2.6649
   at.coord = [150.2462, 116.2796, 86.6618]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 2.7251
   at.coord = [150.3390, 116.1926, 86.6589]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 2.8076
   at.coord = [150.4254, 116.0959, 86.6209]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 2.8089
   at.coord = [150.5044, 115.9879, 86.5428]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 2.7817
   at.coord = [150.5757, 115.8714, 86.4301]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 2.7733
   at.coord = [150.6391, 115.7514, 86.2950]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 2.7811
   at.coord = [150.6946, 115.6329, 86.1498]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 2.8005
   at.coord = [150.7420, 115.5211, 86.0069]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 2.8245
   at.coord = [150.7813, 115.4211, 85.8784]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 2.8405
   at.coord = [150.8123, 115.3380, 85.7768]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 2.8378
   at.coord = [150.8352, 115.2768, 85.7142]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 2.8078
   at.coord = [150.8520, 115.2384, 85.6926]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 2.8060
   at.coord = [150.8685, 115.2171, 85.6984]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 2.8116
   at.coord = [150.8909, 115.2066, 85.7167]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 2.7967
   at.coord = [150.9250, 115.2006, 85.7326]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 2.7967
   at.coord = [150.9771, 115.1929, 85.7312]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 2.8193
   at.coord = [151.0531, 115.1772, 85.6974]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 2.8647
   at.coord = [151.1591, 115.1473, 85.6164]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 2.8107
   at.coord = [151.2982, 115.0990, 85.4783]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 2.7567
   at.coord = [151.4618, 115.0367, 85.2933]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 2.7230
   at.coord = [151.6382, 114.9669, 85.0766]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 2.7161
   at.coord = [151.8158, 114.8959, 84.8435]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 2.7368
   at.coord = [151.9830, 114.8303, 84.6093]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 2.7799
   at.coord = [152.1282, 114.7765, 84.3893]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 2.8368
   at.coord = [152.2398, 114.7411, 84.1986]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 2.8552
   at.coord = [152.3071, 114.7297, 84.0512]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 2.8401
   at.coord = [152.3312, 114.7405, 83.9445]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 2.8088
   at.coord = [152.3205, 114.7665, 83.8653]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 2.7681
   at.coord = [152.2837, 114.8005, 83.8004]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 2.7255
   at.coord = [152.2293, 114.8355, 83.7365]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 2.6896
   at.coord = [152.1659, 114.8645, 83.6601]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 2.6696
   at.coord = [152.1023, 114.8803, 83.5581]
   model.atom.append(at)
   at = Atom()
   at.name = "37"
   at.vdw = 2.6454
   at.coord = [152.0468, 114.8760, 83.4172]
   model.atom.append(at)
   at = Atom()
   at.name = "38"
   at.vdw = 2.5731
   at.coord = [152.0042, 114.8485, 83.2316]
   model.atom.append(at)
   at = Atom()
   at.name = "39"
   at.vdw = 2.5154
   at.coord = [151.9731, 114.8005, 83.0068]
   model.atom.append(at)
   at = Atom()
   at.name = "40"
   at.vdw = 2.4773
   at.coord = [151.9515, 114.7356, 82.7494]
   model.atom.append(at)
   at = Atom()
   at.name = "41"
   at.vdw = 2.4642
   at.coord = [151.9376, 114.6571, 82.4659]
   model.atom.append(at)
   at = Atom()
   at.name = "42"
   at.vdw = 2.4799
   at.coord = [151.9294, 114.5684, 82.1628]
   model.atom.append(at)
   at = Atom()
   at.name = "43"
   at.vdw = 2.5260
   at.coord = [151.9250, 114.4729, 81.8467]
   model.atom.append(at)
   at = Atom()
   at.name = "44"
   at.vdw = 2.6011
   at.coord = [151.9226, 114.3741, 81.5240]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels4")
   cmd.hide("everything","Tunnels4")
   cmd.set("surface_color","olive","Tunnels4")
   cmd.show("surface","Tunnels4")
Tunnels4()
def Tunnels5():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 2.1875
   at.coord = [164.6208, 123.6127, 93.4155]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 2.1561
   at.coord = [164.8671, 123.7148, 93.3483]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 2.1460
   at.coord = [165.0957, 123.8083, 93.2873]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 2.1538
   at.coord = [165.2889, 123.8846, 93.2386]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 2.1732
   at.coord = [165.4289, 123.9349, 93.2083]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 2.1519
   at.coord = [165.5043, 123.9530, 93.1996]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 2.1520
   at.coord = [165.5432, 123.9476, 93.1955]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 2.1478
   at.coord = [165.5884, 123.9328, 93.1719]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 2.1601
   at.coord = [165.6828, 123.9229, 93.1044]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 2.1440
   at.coord = [165.8645, 123.9309, 92.9723]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 2.1219
   at.coord = [166.1241, 123.9593, 92.7890]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 2.1386
   at.coord = [166.4253, 124.0042, 92.5874]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 2.2042
   at.coord = [166.7312, 124.0616, 92.4008]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 2.2684
   at.coord = [167.0063, 124.1276, 92.2609]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 2.2832
   at.coord = [167.2328, 124.1956, 92.1752]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 2.3143
   at.coord = [167.4080, 124.2574, 92.1313]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 2.3216
   at.coord = [167.5296, 124.3044, 92.1161]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 2.3239
   at.coord = [167.5956, 124.3284, 92.1166]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 2.3242
   at.coord = [167.6213, 124.3330, 92.1237]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 2.3255
   at.coord = [167.6419, 124.3357, 92.1324]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 2.3297
   at.coord = [167.6941, 124.3548, 92.1382]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 2.3396
   at.coord = [167.8144, 124.4086, 92.1365]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 2.3592
   at.coord = [168.0127, 124.5011, 92.1259]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 2.4010
   at.coord = [168.2532, 124.6119, 92.1111]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 2.4639
   at.coord = [168.4953, 124.7177, 92.0970]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 2.5215
   at.coord = [168.6983, 124.7956, 92.0886]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 2.4971
   at.coord = [168.8360, 124.8310, 92.0892]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 2.5002
   at.coord = [168.9203, 124.8318, 92.0971]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 2.5182
   at.coord = [168.9688, 124.8096, 92.1098]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 2.5434
   at.coord = [168.9995, 124.7758, 92.1251]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels5")
   cmd.hide("everything","Tunnels5")
   cmd.set("surface_color","purple","Tunnels5")
   cmd.show("surface","Tunnels5")
Tunnels5()
def Tunnels6():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.8828
   at.coord = [133.9907, 121.1563, 108.4083]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.8706
   at.coord = [133.9341, 121.2334, 108.3763]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.8670
   at.coord = [133.8829, 121.3121, 108.3472]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.8773
   at.coord = [133.8428, 121.3939, 108.3240]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.9067
   at.coord = [133.8190, 121.4803, 108.3097]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.9610
   at.coord = [133.8172, 121.5730, 108.3073]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.9650
   at.coord = [133.8425, 121.6735, 108.3191]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.9453
   at.coord = [133.8961, 121.7839, 108.3402]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.9287
   at.coord = [133.9769, 121.9068, 108.3610]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 1.9086
   at.coord = [134.0836, 122.0446, 108.3719]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 1.8791
   at.coord = [134.2151, 122.1997, 108.3632]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 1.8165
   at.coord = [134.3699, 122.3746, 108.3254]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 1.7287
   at.coord = [134.5435, 122.5683, 108.2563]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 1.6707
   at.coord = [134.7262, 122.7744, 108.1648]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 1.6445
   at.coord = [134.9079, 122.9861, 108.0609]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 1.6461
   at.coord = [135.0785, 123.1966, 107.9544]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 1.6649
   at.coord = [135.2276, 123.3992, 107.8554]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 1.6809
   at.coord = [135.3474, 123.5875, 107.7719]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 1.7047
   at.coord = [135.4377, 123.7574, 107.7044]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 1.7304
   at.coord = [135.5007, 123.9052, 107.6516]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 1.7519
   at.coord = [135.5383, 124.0271, 107.6119]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 1.7645
   at.coord = [135.5526, 124.1195, 107.5840]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 1.7651
   at.coord = [135.5464, 124.1795, 107.5665]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 1.7595
   at.coord = [135.5302, 124.2143, 107.5582]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 1.7558
   at.coord = [135.5197, 124.2373, 107.5579]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 1.7487
   at.coord = [135.5308, 124.2622, 107.5645]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.7458
   at.coord = [135.5792, 124.3026, 107.5768]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.7536
   at.coord = [135.6804, 124.3720, 107.5937]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.7469
   at.coord = [135.8400, 124.4762, 107.6141]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.7025
   at.coord = [136.0472, 124.6090, 107.6374]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 1.6756
   at.coord = [136.2902, 124.7633, 107.6628]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 1.6767
   at.coord = [136.5571, 124.9320, 107.6896]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 1.6508
   at.coord = [136.8359, 125.1078, 107.7172]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels6")
   cmd.hide("everything","Tunnels6")
   cmd.set("surface_color","slate","Tunnels6")
   cmd.show("surface","Tunnels6")
Tunnels6()
def Tunnels7():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.4127
   at.coord = [145.1646, 111.3990, 87.2983]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.4358
   at.coord = [145.2092, 111.4497, 87.2741]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.3893
   at.coord = [145.2414, 111.4817, 87.2430]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.3743
   at.coord = [145.2490, 111.4764, 87.1981]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.4177
   at.coord = [145.2197, 111.4148, 87.1327]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.5465
   at.coord = [145.1410, 111.2784, 87.0399]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.6004
   at.coord = [145.0048, 111.0546, 86.9153]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.6934
   at.coord = [144.8269, 110.7688, 86.7704]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.8434
   at.coord = [144.6326, 110.4609, 86.6227]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 2.0247
   at.coord = [144.4471, 110.1708, 86.4894]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 2.1672
   at.coord = [144.2958, 109.9386, 86.3882]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 2.0547
   at.coord = [144.2015, 109.7999, 86.3343]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 2.0128
   at.coord = [144.1628, 109.7502, 86.3232]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 2.0269
   at.coord = [144.1650, 109.7620, 86.3386]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 2.0711
   at.coord = [144.1929, 109.8074, 86.3646]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 2.1200
   at.coord = [144.2314, 109.8588, 86.3849]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 2.1485
   at.coord = [144.2659, 109.8894, 86.3842]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 2.1513
   at.coord = [144.2899, 109.8925, 86.3633]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 2.1395
   at.coord = [144.3034, 109.8779, 86.3359]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 2.1248
   at.coord = [144.3068, 109.8556, 86.3163]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 2.1188
   at.coord = [144.3004, 109.8358, 86.3188]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 2.1327
   at.coord = [144.2845, 109.8285, 86.3568]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 2.1652
   at.coord = [144.2646, 109.8332, 86.4208]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 2.1596
   at.coord = [144.2520, 109.8372, 86.4736]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 2.1495
   at.coord = [144.2582, 109.8268, 86.4760]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 2.1041
   at.coord = [144.2949, 109.7885, 86.3893]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.9952
   at.coord = [144.3737, 109.7090, 86.1747]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.8545
   at.coord = [144.4955, 109.5854, 85.8261]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.7382
   at.coord = [144.6428, 109.4337, 85.3945]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.6883
   at.coord = [144.7965, 109.2716, 84.9368]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 1.7111
   at.coord = [144.9370, 109.1169, 84.5099]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 1.7742
   at.coord = [145.0450, 108.9875, 84.1705]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 1.8114
   at.coord = [145.1084, 108.8948, 83.9550]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 1.7936
   at.coord = [145.1337, 108.8337, 83.8455]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 1.7920
   at.coord = [145.1304, 108.7962, 83.8156]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 1.7994
   at.coord = [145.1080, 108.7744, 83.8387]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 1.8120
   at.coord = [145.0760, 108.7606, 83.8883]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels7")
   cmd.hide("everything","Tunnels7")
   cmd.set("surface_color","marine","Tunnels7")
   cmd.show("surface","Tunnels7")
Tunnels7()
def Tunnels8():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.4166
   at.coord = [132.8734, 122.5573, 141.6845]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.4500
   at.coord = [133.2124, 122.5878, 141.8585]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.5216
   at.coord = [133.5260, 122.6185, 142.0196]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.6089
   at.coord = [133.7890, 122.6496, 142.1549]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.6832
   at.coord = [133.9761, 122.6814, 142.2515]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.6617
   at.coord = [134.0648, 122.7137, 142.2976]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.6416
   at.coord = [134.0731, 122.7411, 142.2992]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.6581
   at.coord = [134.0508, 122.7543, 142.2760]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.6592
   at.coord = [134.0483, 122.7437, 142.2479]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 1.7024
   at.coord = [134.1158, 122.6999, 142.2348]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 1.6990
   at.coord = [134.2752, 122.6214, 142.2494]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 1.6933
   at.coord = [134.4845, 122.5247, 142.2875]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 1.6920
   at.coord = [134.6931, 122.4287, 142.3429]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 1.6888
   at.coord = [134.8505, 122.3522, 142.4093]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 1.6703
   at.coord = [134.9149, 122.3113, 142.4789]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 1.6445
   at.coord = [134.9087, 122.3013, 142.5317]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 1.6337
   at.coord = [134.8833, 122.3081, 142.5426]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 1.6638
   at.coord = [134.8903, 122.3177, 142.4864]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 1.6623
   at.coord = [134.9800, 122.3161, 142.3386]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 1.5894
   at.coord = [135.1642, 122.2981, 142.1004]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 1.5243
   at.coord = [135.4045, 122.2692, 141.8068]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 1.5039
   at.coord = [135.6588, 122.2357, 141.4950]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 1.5335
   at.coord = [135.8853, 122.2039, 141.2022]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 1.5470
   at.coord = [136.0514, 122.1797, 140.9588]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 1.5842
   at.coord = [136.1611, 122.1670, 140.7688]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 1.6342
   at.coord = [136.2278, 122.1691, 140.6291]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.6887
   at.coord = [136.2650, 122.1895, 140.5370]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.7139
   at.coord = [136.2861, 122.2305, 140.4887]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.7392
   at.coord = [136.3075, 122.2789, 140.4696]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.7666
   at.coord = [136.3473, 122.3095, 140.4564]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 1.7737
   at.coord = [136.4241, 122.2968, 140.4255]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 1.7360
   at.coord = [136.5560, 122.2155, 140.3535]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 1.6524
   at.coord = [136.7477, 122.0579, 140.2295]
   model.atom.append(at)
   at = Atom()
   at.name = "33"
   at.vdw = 1.5924
   at.coord = [136.9732, 121.8564, 140.0706]
   model.atom.append(at)
   at = Atom()
   at.name = "34"
   at.vdw = 1.5661
   at.coord = [137.2026, 121.6486, 139.8978]
   model.atom.append(at)
   at = Atom()
   at.name = "35"
   at.vdw = 1.5932
   at.coord = [137.4058, 121.4720, 139.7321]
   model.atom.append(at)
   at = Atom()
   at.name = "36"
   at.vdw = 1.5707
   at.coord = [137.5563, 121.3595, 139.5923]
   model.atom.append(at)
   at = Atom()
   at.name = "37"
   at.vdw = 1.5784
   at.coord = [137.6546, 121.3076, 139.4825]
   model.atom.append(at)
   at = Atom()
   at.name = "38"
   at.vdw = 1.6121
   at.coord = [137.7131, 121.2965, 139.3997]
   model.atom.append(at)
   at = Atom()
   at.name = "39"
   at.vdw = 1.6519
   at.coord = [137.7444, 121.3067, 139.3411]
   model.atom.append(at)
   at = Atom()
   at.name = "40"
   at.vdw = 1.6650
   at.coord = [137.7608, 121.3185, 139.3038]
   model.atom.append(at)
   at = Atom()
   at.name = "41"
   at.vdw = 1.6556
   at.coord = [137.7702, 121.3215, 139.2844]
   model.atom.append(at)
   at = Atom()
   at.name = "42"
   at.vdw = 1.6567
   at.coord = [137.7747, 121.3175, 139.2783]
   model.atom.append(at)
   at = Atom()
   at.name = "43"
   at.vdw = 1.6646
   at.coord = [137.7759, 121.3087, 139.2812]
   model.atom.append(at)
   at = Atom()
   at.name = "44"
   at.vdw = 1.6759
   at.coord = [137.7754, 121.2975, 139.2886]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels8")
   cmd.hide("everything","Tunnels8")
   cmd.set("surface_color","teal","Tunnels8")
   cmd.show("surface","Tunnels8")
Tunnels8()
def Tunnels9():
   model = Indexed()
   at = Atom()
   at.name = "0"
   at.vdw = 1.4594
   at.coord = [133.3785, 148.0625, 109.2934]
   model.atom.append(at)
   at = Atom()
   at.name = "1"
   at.vdw = 1.4722
   at.coord = [133.4443, 147.9008, 109.3390]
   model.atom.append(at)
   at = Atom()
   at.name = "2"
   at.vdw = 1.5013
   at.coord = [133.5027, 147.7387, 109.3839]
   model.atom.append(at)
   at = Atom()
   at.name = "3"
   at.vdw = 1.5512
   at.coord = [133.5464, 147.5759, 109.4273]
   model.atom.append(at)
   at = Atom()
   at.name = "4"
   at.vdw = 1.6257
   at.coord = [133.5680, 147.4120, 109.4685]
   model.atom.append(at)
   at = Atom()
   at.name = "5"
   at.vdw = 1.7026
   at.coord = [133.5604, 147.2469, 109.5068]
   model.atom.append(at)
   at = Atom()
   at.name = "6"
   at.vdw = 1.7521
   at.coord = [133.5251, 147.0838, 109.5411]
   model.atom.append(at)
   at = Atom()
   at.name = "7"
   at.vdw = 1.8010
   at.coord = [133.4741, 146.9306, 109.5701]
   model.atom.append(at)
   at = Atom()
   at.name = "8"
   at.vdw = 1.8491
   at.coord = [133.4199, 146.7953, 109.5923]
   model.atom.append(at)
   at = Atom()
   at.name = "9"
   at.vdw = 1.8946
   at.coord = [133.3752, 146.6859, 109.6063]
   model.atom.append(at)
   at = Atom()
   at.name = "10"
   at.vdw = 1.9161
   at.coord = [133.3503, 146.6088, 109.6113]
   model.atom.append(at)
   at = Atom()
   at.name = "11"
   at.vdw = 1.9180
   at.coord = [133.3430, 146.5603, 109.6094]
   model.atom.append(at)
   at = Atom()
   at.name = "12"
   at.vdw = 1.9259
   at.coord = [133.3457, 146.5328, 109.6039]
   model.atom.append(at)
   at = Atom()
   at.name = "13"
   at.vdw = 1.9342
   at.coord = [133.3512, 146.5189, 109.5981]
   model.atom.append(at)
   at = Atom()
   at.name = "14"
   at.vdw = 1.9376
   at.coord = [133.3521, 146.5109, 109.5955]
   model.atom.append(at)
   at = Atom()
   at.name = "15"
   at.vdw = 1.9348
   at.coord = [133.3452, 146.5024, 109.5966]
   model.atom.append(at)
   at = Atom()
   at.name = "16"
   at.vdw = 1.9311
   at.coord = [133.3346, 146.4884, 109.5977]
   model.atom.append(at)
   at = Atom()
   at.name = "17"
   at.vdw = 1.9327
   at.coord = [133.3250, 146.4645, 109.5946]
   model.atom.append(at)
   at = Atom()
   at.name = "18"
   at.vdw = 1.9459
   at.coord = [133.3211, 146.4260, 109.5829]
   model.atom.append(at)
   at = Atom()
   at.name = "19"
   at.vdw = 1.9704
   at.coord = [133.3266, 146.3692, 109.5593]
   model.atom.append(at)
   at = Atom()
   at.name = "20"
   at.vdw = 2.0015
   at.coord = [133.3353, 146.2985, 109.5290]
   model.atom.append(at)
   at = Atom()
   at.name = "21"
   at.vdw = 2.0169
   at.coord = [133.3352, 146.2231, 109.5021]
   model.atom.append(at)
   at = Atom()
   at.name = "22"
   at.vdw = 2.0278
   at.coord = [133.3142, 146.1523, 109.4889]
   model.atom.append(at)
   at = Atom()
   at.name = "23"
   at.vdw = 1.9901
   at.coord = [133.2602, 146.0953, 109.4994]
   model.atom.append(at)
   at = Atom()
   at.name = "24"
   at.vdw = 1.9123
   at.coord = [133.1754, 146.0526, 109.5364]
   model.atom.append(at)
   at = Atom()
   at.name = "25"
   at.vdw = 1.8346
   at.coord = [133.0990, 146.0012, 109.5834]
   model.atom.append(at)
   at = Atom()
   at.name = "26"
   at.vdw = 1.8050
   at.coord = [133.0759, 145.9145, 109.6206]
   model.atom.append(at)
   at = Atom()
   at.name = "27"
   at.vdw = 1.8738
   at.coord = [133.1513, 145.7659, 109.6282]
   model.atom.append(at)
   at = Atom()
   at.name = "28"
   at.vdw = 1.8397
   at.coord = [133.3679, 145.5302, 109.5876]
   model.atom.append(at)
   at = Atom()
   at.name = "29"
   at.vdw = 1.6445
   at.coord = [133.7260, 145.2077, 109.4969]
   model.atom.append(at)
   at = Atom()
   at.name = "30"
   at.vdw = 1.5067
   at.coord = [134.1910, 144.8196, 109.3683]
   model.atom.append(at)
   at = Atom()
   at.name = "31"
   at.vdw = 1.5050
   at.coord = [134.7274, 144.3878, 109.2144]
   model.atom.append(at)
   at = Atom()
   at.name = "32"
   at.vdw = 1.6770
   at.coord = [135.2994, 143.9340, 109.0479]
   model.atom.append(at)
   for a in range(len(model.atom)-1):
      bd = Bond()
      bd.index = [a,a+1]
      model.bond.append(bd)
   cmd.set("surface_mode",1)
   cmd.set("sphere_mode",5)
   cmd.set("mesh_mode",1)
   cmd.load_model(model,"Tunnels9")
   cmd.hide("everything","Tunnels9")
   cmd.set("surface_color","violet","Tunnels9")
   cmd.show("surface","Tunnels9")
Tunnels9()
def PdbLoadCommand():
   pdbCode = '7rpi'
   pdbCode = pdbCode.upper()
   cmd.fetch(pdbCode)
PdbLoadCommand()
